services:
#    usuario.example:
#        class: crisal\UsuarioBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    login_listener:
        class: crisal\UsuarioBundle\Listener\LoginListener
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
